### ISSUE TITLE
How to use the project in Delphi 7

### ISSUE THREAD

**Issue by erickmajor** [wendelb/DelphiOTP#2]
Hello!

How can I use your project in a Delphi 7 system?

Could you leave a sample project in the **examples** folder?

Thank you very much!

**Comment by wendelb** [comment]
Hey there!

I can definitely add an example. Since I don't have any Delphi 7 copy anymore, this example ill be in a newer Delphi version. I'm sure, this can be adapted to your needs.
Since I'm doing this in my spare time and there isn't much lately, it might take some time for me to do it.

Kind regards.

**Comment by wendelb** [comment]
There is now an example project in the `Example` folder. Give me a note if it doesn't work in your environment.

Regards.

**Comment by erickmajor** [comment]
Good morning @wendelb,

I apologize for the delay in answering. I have not had access to a Windows computer this weekend to test its example.

I made a fork of your code to be able to commit some modifications related to the environment Delphi 7. Unfortunately it depends on the environment the library used is the Indy 10, which made it impossible to compile on my machine.

Is there a way to put the used libraries without needing the Indy library?

Thank you for your attention.

**Comment by erickmajor** [comment]
Since I can not update the Indy library from version 9 to 10, because of my projects, I researched the subject.

The @skelter user provides the files for compiling the older Indy 10 library for Delphi [here](https://github.com/skelter/Indy).

**Comment by wendelb** [comment]
>is there a way to put the used libraries without needing the Indy library? 
I'm importing the TId*-Class for HMAC-SHA1 from Indy. Can't say whether there is one available in Indy 9. So in order to compile, you would need another Library that gives you the HMAC-SHA1-Algorithm. If I were you, I would have a look at the Delphi Encryption Compendium. There might be something in there.

**Comment by erickmajor** [comment]
Thanks for the quick reply, @wendelb

I have already verified that there is no algorithm for HMAC-SHA1 encryption in the Indy 9 library.

I'll search more about it and check if I can compile in Delphi 7. Thanks for the great tip.

**Comment by skelter** [comment]
Please remember: go back to http://www.indyproject.org/sockets/download/svn.en.aspx for authoritative source.  My clone into git was 4 jobs ago.
